version: '3'

tasks:
  default:
    desc: show commands
    cmds:
      - task -l --sort none

  format:
    desc: format code
    cmds:
      - uv run ruff format apps
      - pnpm biome format --write apps packages
  lint:
    desc: lint code
    cmds:
      - uv run ruff check --fix apps
      - pnpm biome lint --write apps packages
  typecheck:
    desc: typecheck
    cmds:
      - uv run mypy src --ignore-missing-imports
  qualify:
    desc: qualify code
    cmds:
      - task format
      - task lint
      # - task typecheck

